---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: show virtualization type fot Ansible role testing
      ansible.builtin.debug:
        msg: "{{ ansible_virtualization_type }}"

  roles:
    - role: "ansible-role-swap"
